services:
  - type: web
    name: monster-price-tracker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    envVars:
      - key: FLASK_ENV
        value: production
