services:
  - type: web
    name: monster-price-tracker
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y wget unzip
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      apt-get install -y ./google-chrome-stable_current_amd64.deb
      pip install -r requirements.txt
    startCommand: "python server.py"
    envVars:
      - key: FLASK_ENV
        value: production
