name = "monster-price-tracker"
type = "javascript"

account_id = "your-cloudflare-account-id"  # Replace with your Cloudflare account ID
workers_dev = true

main = "./worker.js"  # Replace with the path to your worker script

[env.production]
route = "your-domain.com/*"  # Replace with your domain
zone_id = "your-zone-id"  # Replace with your Cloudflare zone ID
